export const INIT  = 'INIT'
export const LOGIN = 'LOGIN'
export const GOT_VERIFYCODE = 'GOT_VERIFYCODE'
export const REGISTER_DONE = 'REGISTER_DONE'
export const RESET_PASSWORD_DONE = 'RESET_PASSWORD_DONE'
