export const INIT_ARTICLE_LIST = 'INIT_ARTICLE_LIST'

export const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL'

export const ADD_ARTICLE_LIST = 'ADD_ARTICLE_LIST'

export const CHANGE_ARTICLE_LIST_TOTAL = 'CHANGE_ARTICLE_LIST_TOTAL'

export const CHANGE_ARTICLES_PAGE_NO = 'CHANGE_ARTICLES_PAGE_NO'
