export const GET_ORDER_LIST = 'GET_ORDER_LIST'

export const GET_ORDER_DETAIL = 'GET_ORDER_DETAIL'

export const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS'

export const GET_ORDER_STATUS_COUNT = 'GET_ORDER_STATUS_COUNT'
