export const SET_REFUND_LIST_PAGE = 'SET_REFUND_LIST_PAGE'

export const GET_REFUND_LIST = 'GET_REFUND_LIST'

export const GET_REFUND_DETAIL = 'GET_REFUND_DETAIL'

export const GET_REFUND_TRACE = 'GET_REFUND_TRACE'
