export const GET_SEARCH_LIST = 'GET_SEARCH_LIST'

export const CHANGE_SEARCH_PAGE_NO = 'CHANGE_SEARCH_PAGE_NO'

export const CHANGE_SEARCH_LIST_TOTAL = 'CHANGE_SEARCH_LIST_TOTAL'

export const LOAD_MORE_SEARCH_LIST = 'LOAD_MORE_SEARCH_LIST'
