export const GET_SHOWCASE_LIST = 'GET_SHOWCASE_LIST'

export const GET_SHOWCASE_TEMPLATE = 'GET_SHOWCASE_TEMPLATE'

export const INIT_SHOWCASE = 'INIT_SHOWCASE'

export const UPDATE_SHOWCASE_INDEX = 'UPDATE_SHOWCASE_INDEX'
